export const SHEET_HEADERS = [
  'newsletter_issue_date',
  'month',
  'year',
  'crca_bundle_mumbai',
  'crca_bundle_chennai',
  'melting_foundry_scrap_mumbai',
  'fe_mn_hc_mumbai',
  'fe_si_70_75_mumbai',
  'low_sulp_cal_petro_coke',
  'fe_si_mg_mumbai',
  'cu_lme',
  'cu_domestic',
  'fe_cr_mumbai',
  'pig_iron_foundry_gr_pune',
  'source_pages',
];
